"""Add flagged field to User and Campaign models

Revision ID: 410001737fe9
Revises: 8a9f8c7efa3e
Create Date: 2024-09-18 23:58:04.795568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410001737fe9'
down_revision = '8a9f8c7efa3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flagged', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flagged', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('flagged')

    with op.batch_alter_table('campaign', schema=None) as batch_op:
        batch_op.drop_column('flagged')

    # ### end Alembic commands ###
