"""requirements datatype change

Revision ID: 66610f8c42b4
Revises: 7ffe10ad44e9
Create Date: 2024-09-20 01:00:46.468959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66610f8c42b4'
down_revision = '7ffe10ad44e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_request', schema=None) as batch_op:
        batch_op.alter_column('requirements',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_request', schema=None) as batch_op:
        batch_op.alter_column('requirements',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
